service: dw-test-task-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

functions:
  handle-message:
    handler: src/handler.handler
    events:
      - http: GET /
        cors: true

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    webpackConfig: webpack.config.ts
    includeModules: true
